### ISSUE TITLE
Function result saving to .mat files

### ISSUE THREAD

**Issue by geezIIT** [geez0x1/CompliantJointToolbox#7]
Functions like `getLinearDOB`, `getLinearDOB_fromData`, `getKalman`, `getObserver`, `get_controlled_closed_loop`, and `design_DOB_controller` should either all save their results to .mat files in a consistent way, or not at all (to be handled by the caller).

**Comment by geez0x1** [comment]
Fixed in 1b1d3b0afdafe14478b212c17fbe4b92d1395df3 and faf63fcb1d27ed61a75ce0d873bd4ace0008210e. The functions `getLinearDOB`, `getLinearDOB_fromData`, and `design_DOB_controller` now do not ask to save their results any more, since it causes problems when calling these functions from Simulink block masks. All saving should be handled by the caller.
